### ISSUE TITLE
关于IBM DS课程 SQL课后题的疑问

### ISSUE THREAD

**Issue by Chu4nQ1n** [ZihengZZH/data-science-IBM#1]
您好，感谢您阅读我的提问。

该课程Week3的课后题Quiz2的第二题我有点不明白，
![image](https://user-images.githubusercontent.com/33832002/134828859-4276e330-b6d0-40d2-bad3-c32b0b13abd3.png)
为什么这里的WHERE DEPT_ID_DEP = DEP_ID 前面不需要指明table的对象呢，我认为D选项应该是最合适的。

课程中给出的例子如下：
![image](https://user-images.githubusercontent.com/33832002/134828912-b6daa6b6-a1b1-4960-b8e6-66b2fa04c83f.png)

恳请您能在百忙之中回答我的问题，谢谢。

**Comment by Chu4nQ1n** [comment]
我看到您给出的答案也是D选项（在SELECT中也使用了table.cloumn），但Coursera上的标准答案是C选项，请问是答案给错了吗

**Comment by ZihengZZH** [comment]
> 我看到您给出的答案也是D选项（在SELECT中也使用了table.cloumn），但Coursera上的标准答案是C选项，请问是答案给错了吗

Sorry for the late reply.

因为时间太久我也不太记得细节了，你可以咨询一下课程相关instructor或者TA。
